import Head from "next/head";
import type { NextPage } from "next";
import styles from "../styles/Home.module.css";

// const getData = () => {
//   const resp = axios.get("/").catch((err: any) => console.log(err));
// };

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Trading Bot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Kayseri Krypto Kulubu</h1>

        <p className={styles.description}>
          Turkeys answer to dollar cost average trading
        </p>

        <div className={styles.grid}></div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Brought to you by the Hallo Bros.
        </a>
      </footer>
    </div>
  );
};

export default Home;
